/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardLeadsRouteImport } from './routes/dashboard.leads'
import { Route as DashboardFirmSlugRouteImport } from './routes/dashboard.$firmSlug'
import { Route as AskFirmSlugRouteImport } from './routes/ask.$firmSlug'
import { Route as AdminTenantsRouteImport } from './routes/admin.tenants'
import { Route as DashboardFirmSlugIndexRouteImport } from './routes/dashboard.$firmSlug.index'
import { Route as DashboardFirmSlugLeadsRouteImport } from './routes/dashboard.$firmSlug.leads'
import { Route as DashboardFirmSlugConversationsRouteImport } from './routes/dashboard.$firmSlug.conversations'
import { Route as DashboardFirmSlugContentRouteImport } from './routes/dashboard.$firmSlug.content'
import { Route as DashboardFirmSlugLeadsIndexRouteImport } from './routes/dashboard.$firmSlug.leads.index'
import { Route as DashboardFirmSlugConversationsIndexRouteImport } from './routes/dashboard.$firmSlug.conversations.index'
import { Route as DashboardFirmSlugLeadsConversationIdRouteImport } from './routes/dashboard.$firmSlug.leads.$conversationId'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLeadsRoute = DashboardLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFirmSlugRoute = DashboardFirmSlugRouteImport.update({
  id: '/$firmSlug',
  path: '/$firmSlug',
  getParentRoute: () => DashboardRoute,
} as any)
const AskFirmSlugRoute = AskFirmSlugRouteImport.update({
  id: '/ask/$firmSlug',
  path: '/ask/$firmSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTenantsRoute = AdminTenantsRouteImport.update({
  id: '/admin/tenants',
  path: '/admin/tenants',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardFirmSlugIndexRoute = DashboardFirmSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardFirmSlugRoute,
} as any)
const DashboardFirmSlugLeadsRoute = DashboardFirmSlugLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => DashboardFirmSlugRoute,
} as any)
const DashboardFirmSlugConversationsRoute =
  DashboardFirmSlugConversationsRouteImport.update({
    id: '/conversations',
    path: '/conversations',
    getParentRoute: () => DashboardFirmSlugRoute,
  } as any)
const DashboardFirmSlugContentRoute =
  DashboardFirmSlugContentRouteImport.update({
    id: '/content',
    path: '/content',
    getParentRoute: () => DashboardFirmSlugRoute,
  } as any)
const DashboardFirmSlugLeadsIndexRoute =
  DashboardFirmSlugLeadsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardFirmSlugLeadsRoute,
  } as any)
const DashboardFirmSlugConversationsIndexRoute =
  DashboardFirmSlugConversationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardFirmSlugConversationsRoute,
  } as any)
const DashboardFirmSlugLeadsConversationIdRoute =
  DashboardFirmSlugLeadsConversationIdRouteImport.update({
    id: '/$conversationId',
    path: '/$conversationId',
    getParentRoute: () => DashboardFirmSlugLeadsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/admin/tenants': typeof AdminTenantsRoute
  '/ask/$firmSlug': typeof AskFirmSlugRoute
  '/dashboard/$firmSlug': typeof DashboardFirmSlugRouteWithChildren
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/$firmSlug/content': typeof DashboardFirmSlugContentRoute
  '/dashboard/$firmSlug/conversations': typeof DashboardFirmSlugConversationsRouteWithChildren
  '/dashboard/$firmSlug/leads': typeof DashboardFirmSlugLeadsRouteWithChildren
  '/dashboard/$firmSlug/': typeof DashboardFirmSlugIndexRoute
  '/dashboard/$firmSlug/leads/$conversationId': typeof DashboardFirmSlugLeadsConversationIdRoute
  '/dashboard/$firmSlug/conversations/': typeof DashboardFirmSlugConversationsIndexRoute
  '/dashboard/$firmSlug/leads/': typeof DashboardFirmSlugLeadsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/admin/tenants': typeof AdminTenantsRoute
  '/ask/$firmSlug': typeof AskFirmSlugRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/$firmSlug/content': typeof DashboardFirmSlugContentRoute
  '/dashboard/$firmSlug': typeof DashboardFirmSlugIndexRoute
  '/dashboard/$firmSlug/leads/$conversationId': typeof DashboardFirmSlugLeadsConversationIdRoute
  '/dashboard/$firmSlug/conversations': typeof DashboardFirmSlugConversationsIndexRoute
  '/dashboard/$firmSlug/leads': typeof DashboardFirmSlugLeadsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/admin/tenants': typeof AdminTenantsRoute
  '/ask/$firmSlug': typeof AskFirmSlugRoute
  '/dashboard/$firmSlug': typeof DashboardFirmSlugRouteWithChildren
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/$firmSlug/content': typeof DashboardFirmSlugContentRoute
  '/dashboard/$firmSlug/conversations': typeof DashboardFirmSlugConversationsRouteWithChildren
  '/dashboard/$firmSlug/leads': typeof DashboardFirmSlugLeadsRouteWithChildren
  '/dashboard/$firmSlug/': typeof DashboardFirmSlugIndexRoute
  '/dashboard/$firmSlug/leads/$conversationId': typeof DashboardFirmSlugLeadsConversationIdRoute
  '/dashboard/$firmSlug/conversations/': typeof DashboardFirmSlugConversationsIndexRoute
  '/dashboard/$firmSlug/leads/': typeof DashboardFirmSlugLeadsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/admin/tenants'
    | '/ask/$firmSlug'
    | '/dashboard/$firmSlug'
    | '/dashboard/leads'
    | '/dashboard/$firmSlug/content'
    | '/dashboard/$firmSlug/conversations'
    | '/dashboard/$firmSlug/leads'
    | '/dashboard/$firmSlug/'
    | '/dashboard/$firmSlug/leads/$conversationId'
    | '/dashboard/$firmSlug/conversations/'
    | '/dashboard/$firmSlug/leads/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/admin/tenants'
    | '/ask/$firmSlug'
    | '/dashboard/leads'
    | '/dashboard/$firmSlug/content'
    | '/dashboard/$firmSlug'
    | '/dashboard/$firmSlug/leads/$conversationId'
    | '/dashboard/$firmSlug/conversations'
    | '/dashboard/$firmSlug/leads'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/admin/tenants'
    | '/ask/$firmSlug'
    | '/dashboard/$firmSlug'
    | '/dashboard/leads'
    | '/dashboard/$firmSlug/content'
    | '/dashboard/$firmSlug/conversations'
    | '/dashboard/$firmSlug/leads'
    | '/dashboard/$firmSlug/'
    | '/dashboard/$firmSlug/leads/$conversationId'
    | '/dashboard/$firmSlug/conversations/'
    | '/dashboard/$firmSlug/leads/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  AdminTenantsRoute: typeof AdminTenantsRoute
  AskFirmSlugRoute: typeof AskFirmSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/leads': {
      id: '/dashboard/leads'
      path: '/leads'
      fullPath: '/dashboard/leads'
      preLoaderRoute: typeof DashboardLeadsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/$firmSlug': {
      id: '/dashboard/$firmSlug'
      path: '/$firmSlug'
      fullPath: '/dashboard/$firmSlug'
      preLoaderRoute: typeof DashboardFirmSlugRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/ask/$firmSlug': {
      id: '/ask/$firmSlug'
      path: '/ask/$firmSlug'
      fullPath: '/ask/$firmSlug'
      preLoaderRoute: typeof AskFirmSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tenants': {
      id: '/admin/tenants'
      path: '/admin/tenants'
      fullPath: '/admin/tenants'
      preLoaderRoute: typeof AdminTenantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$firmSlug/': {
      id: '/dashboard/$firmSlug/'
      path: '/'
      fullPath: '/dashboard/$firmSlug/'
      preLoaderRoute: typeof DashboardFirmSlugIndexRouteImport
      parentRoute: typeof DashboardFirmSlugRoute
    }
    '/dashboard/$firmSlug/leads': {
      id: '/dashboard/$firmSlug/leads'
      path: '/leads'
      fullPath: '/dashboard/$firmSlug/leads'
      preLoaderRoute: typeof DashboardFirmSlugLeadsRouteImport
      parentRoute: typeof DashboardFirmSlugRoute
    }
    '/dashboard/$firmSlug/conversations': {
      id: '/dashboard/$firmSlug/conversations'
      path: '/conversations'
      fullPath: '/dashboard/$firmSlug/conversations'
      preLoaderRoute: typeof DashboardFirmSlugConversationsRouteImport
      parentRoute: typeof DashboardFirmSlugRoute
    }
    '/dashboard/$firmSlug/content': {
      id: '/dashboard/$firmSlug/content'
      path: '/content'
      fullPath: '/dashboard/$firmSlug/content'
      preLoaderRoute: typeof DashboardFirmSlugContentRouteImport
      parentRoute: typeof DashboardFirmSlugRoute
    }
    '/dashboard/$firmSlug/leads/': {
      id: '/dashboard/$firmSlug/leads/'
      path: '/'
      fullPath: '/dashboard/$firmSlug/leads/'
      preLoaderRoute: typeof DashboardFirmSlugLeadsIndexRouteImport
      parentRoute: typeof DashboardFirmSlugLeadsRoute
    }
    '/dashboard/$firmSlug/conversations/': {
      id: '/dashboard/$firmSlug/conversations/'
      path: '/'
      fullPath: '/dashboard/$firmSlug/conversations/'
      preLoaderRoute: typeof DashboardFirmSlugConversationsIndexRouteImport
      parentRoute: typeof DashboardFirmSlugConversationsRoute
    }
    '/dashboard/$firmSlug/leads/$conversationId': {
      id: '/dashboard/$firmSlug/leads/$conversationId'
      path: '/$conversationId'
      fullPath: '/dashboard/$firmSlug/leads/$conversationId'
      preLoaderRoute: typeof DashboardFirmSlugLeadsConversationIdRouteImport
      parentRoute: typeof DashboardFirmSlugLeadsRoute
    }
  }
}

interface DashboardFirmSlugConversationsRouteChildren {
  DashboardFirmSlugConversationsIndexRoute: typeof DashboardFirmSlugConversationsIndexRoute
}

const DashboardFirmSlugConversationsRouteChildren: DashboardFirmSlugConversationsRouteChildren =
  {
    DashboardFirmSlugConversationsIndexRoute:
      DashboardFirmSlugConversationsIndexRoute,
  }

const DashboardFirmSlugConversationsRouteWithChildren =
  DashboardFirmSlugConversationsRoute._addFileChildren(
    DashboardFirmSlugConversationsRouteChildren,
  )

interface DashboardFirmSlugLeadsRouteChildren {
  DashboardFirmSlugLeadsConversationIdRoute: typeof DashboardFirmSlugLeadsConversationIdRoute
  DashboardFirmSlugLeadsIndexRoute: typeof DashboardFirmSlugLeadsIndexRoute
}

const DashboardFirmSlugLeadsRouteChildren: DashboardFirmSlugLeadsRouteChildren =
  {
    DashboardFirmSlugLeadsConversationIdRoute:
      DashboardFirmSlugLeadsConversationIdRoute,
    DashboardFirmSlugLeadsIndexRoute: DashboardFirmSlugLeadsIndexRoute,
  }

const DashboardFirmSlugLeadsRouteWithChildren =
  DashboardFirmSlugLeadsRoute._addFileChildren(
    DashboardFirmSlugLeadsRouteChildren,
  )

interface DashboardFirmSlugRouteChildren {
  DashboardFirmSlugContentRoute: typeof DashboardFirmSlugContentRoute
  DashboardFirmSlugConversationsRoute: typeof DashboardFirmSlugConversationsRouteWithChildren
  DashboardFirmSlugLeadsRoute: typeof DashboardFirmSlugLeadsRouteWithChildren
  DashboardFirmSlugIndexRoute: typeof DashboardFirmSlugIndexRoute
}

const DashboardFirmSlugRouteChildren: DashboardFirmSlugRouteChildren = {
  DashboardFirmSlugContentRoute: DashboardFirmSlugContentRoute,
  DashboardFirmSlugConversationsRoute:
    DashboardFirmSlugConversationsRouteWithChildren,
  DashboardFirmSlugLeadsRoute: DashboardFirmSlugLeadsRouteWithChildren,
  DashboardFirmSlugIndexRoute: DashboardFirmSlugIndexRoute,
}

const DashboardFirmSlugRouteWithChildren =
  DashboardFirmSlugRoute._addFileChildren(DashboardFirmSlugRouteChildren)

interface DashboardRouteChildren {
  DashboardFirmSlugRoute: typeof DashboardFirmSlugRouteWithChildren
  DashboardLeadsRoute: typeof DashboardLeadsRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardFirmSlugRoute: DashboardFirmSlugRouteWithChildren,
  DashboardLeadsRoute: DashboardLeadsRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  AdminTenantsRoute: AdminTenantsRoute,
  AskFirmSlugRoute: AskFirmSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
